# -*- coding: utf-8 -*-
"""heart_desease.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QIP0A3ALXVG6vdM9fu423Ep0_ey7oKXp
"""

import pandas as pd

# 1. Ler o conjunto de dados para um DataFrame
url = 'heart.csv'
df = pd.read_csv(url, sep=',')


# 2. Verificar as primeiras linhas do DataFrame usando `head()`
print("[Primeiras linhas do DataFrame:]\n")
print(df.head())

# 3. Verificar as últimas linhas do DataFrame usando `tail()`
print("\n[Últimas linhas do DataFrame:]\n")
print(df.tail())

# 4. Verificar as dimensões do DataFrame usando `shape`
print("\n[Dimensões do DataFrame:]\n")
print(df.shape)

# 5. Verificar as informações sobre as colunas do DataFrame usando `info()`
print("\n[Informações sobre as colunas do DataFrame:]\n")
print(df.info())

# 6. Verificar as estatísticas descritivas básicas do DataFrame usando `describe()`
print("\n[Estatísticas descritivas do DataFrame:]\n")
print(df.describe())

# 7. Selecionar colunas específicas do DataFrame usando colchetes `[]` ou o método `loc[]`
print("\n[Selecionar colunas específicas do DataFrame:]\n")
selecionar_coluna = df[['age', 'sex', 'chol']]
print(selecionar_coluna.head())

# 8. Selecionar linhas específicas do DataFrame usando o método `loc[]`
print("\n[Selecionar linhas específicas do DataFrame:]\n")
selecionar_linha = df.loc[[0, 3, 6]]
print(selecionar_linha)
